# Generated by Django 4.1.4 on 2023-01-02 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("location", models.CharField(db_index=True, max_length=200)),
                ("address", models.TextField(max_length=50)),
                ("image", models.ImageField(upload_to="images/%Y/%m/%d/")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "index_together": {("id", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("image", models.ImageField(upload_to="images/%Y/%m/%d/")),
                ("description", models.TextField(blank=True, max_length=50)),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("Vegan", "Vegan"),
                            ("Veg", "Veg"),
                            ("Non-veg", "Non-veg"),
                        ],
                        default="Veg",
                        max_length=10,
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                        ],
                        default="Breakfast",
                        max_length=10,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_food_items",
                        to="manageEAT.restaurant",
                    ),
                ),
            ],
        ),
    ]
