# Generated by Django 4.1.4 on 2023-01-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manageEAT", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(upload_to="media/%Y/%m/%d/"),
        ),
    ]
